"""Valeurs par défaut de la configuration VoxWave."""

# 99 langues supportées par Whisper, triées alphabétiquement par nom natif.
# Source : openai/whisper tokenizer.py
WHISPER_LANGUAGES: list[tuple[str, str]] = [
    ("af", "Afrikaans"),
    ("sq", "Shqip"),
    ("am", "አማርኛ"),
    ("ar", "العربية"),
    ("hy", "Հայերեն"),
    ("az", "Azərbaycan"),
    ("ba", "Bashkir"),
    ("eu", "Euskara"),
    ("be", "Беларуская"),
    ("bn", "বাংলা"),
    ("bs", "Bosanski"),
    ("br", "Brezhoneg"),
    ("bg", "Български"),
    ("ca", "Català"),
    ("zh", "中文"),
    ("hr", "Hrvatski"),
    ("cs", "Čeština"),
    ("da", "Dansk"),
    ("nl", "Nederlands"),
    ("en", "English"),
    ("et", "Eesti"),
    ("fo", "Føroyskt"),
    ("fi", "Suomi"),
    ("fr", "Français"),
    ("gl", "Galego"),
    ("ka", "ქართული"),
    ("de", "Deutsch"),
    ("el", "Ελληνικά"),
    ("gu", "ગુજરાતી"),
    ("ht", "Kreyòl ayisyen"),
    ("ha", "Hausa"),
    ("haw", "ʻŌlelo Hawaiʻi"),
    ("he", "עברית"),
    ("hi", "हिन्दी"),
    ("hu", "Magyar"),
    ("is", "Íslenska"),
    ("id", "Bahasa Indonesia"),
    ("it", "Italiano"),
    ("ja", "日本語"),
    ("jw", "Basa Jawa"),
    ("kn", "ಕನ್ನಡ"),
    ("kk", "Қазақ"),
    ("km", "ខ្មែរ"),
    ("ko", "한국어"),
    ("lo", "ລາວ"),
    ("la", "Latina"),
    ("lv", "Latviešu"),
    ("ln", "Lingála"),
    ("lt", "Lietuvių"),
    ("lb", "Lëtzebuergesch"),
    ("mk", "Македонски"),
    ("mg", "Malagasy"),
    ("ms", "Bahasa Melayu"),
    ("ml", "മലയാളം"),
    ("mt", "Malti"),
    ("mi", "Te Reo Māori"),
    ("mr", "मराठी"),
    ("mn", "Монгол"),
    ("my", "မြန်မာ"),
    ("ne", "नेपाली"),
    ("no", "Norsk"),
    ("nn", "Nynorsk"),
    ("oc", "Occitan"),
    ("ps", "پښتو"),
    ("fa", "فارسی"),
    ("pl", "Polski"),
    ("pt", "Português"),
    ("pa", "ਪੰਜਾਬੀ"),
    ("ro", "Română"),
    ("ru", "Русский"),
    ("sa", "संस्कृत"),
    ("sr", "Српски"),
    ("sn", "chiShona"),
    ("sd", "سنڌي"),
    ("si", "සිංහල"),
    ("sk", "Slovenčina"),
    ("sl", "Slovenščina"),
    ("so", "Soomaali"),
    ("es", "Español"),
    ("su", "Basa Sunda"),
    ("sw", "Kiswahili"),
    ("sv", "Svenska"),
    ("tl", "Filipino"),
    ("tg", "Тоҷикӣ"),
    ("ta", "தமிழ்"),
    ("tt", "Татар"),
    ("te", "తెలుగు"),
    ("th", "ภาษาไทย"),
    ("bo", "བོད་སྐད་"),
    ("tr", "Türkçe"),
    ("tk", "Türkmen"),
    ("uk", "Українська"),
    ("ur", "اردو"),
    ("uz", "Oʻzbek"),
    ("vi", "Tiếng Việt"),
    ("as", "অসমীয়া"),
    ("cy", "Cymraeg"),
    ("yi", "ייִדיש"),
    ("yo", "Yorùbá"),
]

DEFAULT_CONFIG: dict = {
    "first_launch": True,
    "hotkey": "F8",
    "language": "en",
    "activation_method": "both",
    "model": "base",
    "injection": "paste",
    "hotkey_debounce": 0.5,
    "audio": {
        "sample_rate": 16000,
        "channels": 1,
        "chunk_size": 512,
        "silence_threshold": 0.01,
        "min_speech_duration": 0.5,
        "min_audio_duration": 0.5,
        "max_audio_duration": 300.0,
        "vad_aggressiveness": 2,
        "chunking_threshold": 30.0,
        "device_id": None,
        "auto_stop_enabled": False,
        "auto_stop_silence_duration": 2.0,
        "feedback": {
            "enabled": True,
            "volume": 0.5,
        },
    },
    "transcription": {
        "provider": "hybrid",
    },
    "whisper": {
        "model": "base",
        "beam_size": 5,
        "vad_filter": False,
        "language": "en",
    },
    "groq": {
        "model": "whisper-large-v3-turbo",
    },
    # cleaning.mode: "raw" (brut, zero traitement) | "auto" (détection app → regex ou LLM contextuel)
    "cleaning": {
        "mode": "auto",
        "provider": "hybrid",
        "cloud_model": "gpt-4o-mini",
        "llm_model": "gemma3:4b",
        "llm_timeout": 5,
        "ollama_host": "http://localhost:11434",
        "filler_words": [
            "euh", "heu", "hum", "ben", "bah", "genre",
            "du coup", "en fait", "tu vois", "quoi", "voilà",
            "comment dire",
        ],
    },
    "gui": {
        "show_transcription_preview": True,
    },
    "licensing": {
        "provider": "lemonsqueezy",
        "free_limit": 1000,
        "free_daily_limit": 9999,
        "cache_duration": 86400,
    },
}
